name: epub_kit
description: Epub Reader and Writer for Dart.
version: 1.0.0
homepage: https://acmesoftware.com
repository: https://github.com/AcmeSoftwareLLC/epub_kit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.6
  quiver: ^3.2.1
  xml: ^6.2.2
  image: ^4.0.15
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
